server:
  port: 8080
  servlet:
    context-path: /cinema-sys
spring:
  jpa:
    show-sql: true
    database: POSTGRESQL
    database-platform: postgres
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    date-format: yyyy-MM-dd hh:mm:ss a
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.99.100:5432/CinemaCurso
    username: postgres
    password: postgres